#!/bin/bash

declare -A files
export files

IFS=$'\n' file_names=($(git ls-files))
for file in "${file_names[@]}"; do
    files["$file"]="$HOME/.$file"
done

unset files[assocs] \
      files[diff] \
      files[ln] \
      files[ls]
