#!/bin/bash

. assocs

for file in "$@"; do
    for subs in "${!files[@]}"; do
        if [[ "$subs" == "$file"* ]]; then
            # echo "$file, $subs -> $dest"
            dest="${files[$subs]}"
            mkdir -p "$(dirname "$dest")"
            ln -sfrvT "$subs" "$dest"
        fi
    done
done
